---
title: "Week 4 - Grammar Extensions"
author: "Aaron Schram"
format: pdf
editor: visual
---

We have now read several articles where the authors have made modifications or extensions to the framework or classes for the *Grammar of Graphics* (Wilkinson, 2005). These extensions come up for a variety of reasons. For example, ggplot in R added the concept of layers to the grammar (Wickham, 2010). This allowed users to overlay visuals onto created graphs using the exact same framework, instead of only using faceted graphs. More recently, VanderPlas *et al* (2023) incorporated generalized parallel coordinate plots as an extension of ggplot and as a result an extension to the grammar. Others such as Chen *et al* (2022) and L'Yi *et al* (2022) have created their own extensions Nebula and Gosling, respectively. It is not that the Grammar of Graphics is inherently flawed, but more that the original basis for the grammar was basic for the design ideas at the time. Parallel coordinate plots are used to view multivariate data by using a projection space to simplify the dimensionality of our data (VanderPlas *et al*, 2023). As another example, Gosling incorporates high dimensional plotting and organization of genetic data using Vega-Lite and JSON files.

Overall, the fault of the Grammar of Graphics is that the original design was not robust enough to include all data types, layers, and other multivariate type designs. These extensions can be seen as just reframing the grammar in some instances, such as parallel coordinate plots changing the coordinate grid and geometry to the projection space using parallel axes, ordering of cases, and scaling of variables. However, this still fails to make use of the first two classes within the function itself, and it does make use of layers. So, this is an example of reframing the original grammar and simultaneously expanding it with the inclusion of repeating layers. Meanwhile, Gosling specifically builds off Vega-Lite with Views and Tracks, where they define Views as primitive building blocks, like marks and channels, and Tracks are related to the actual encoding and representation of the genomic data (L'Yi *et al*, 2022). Here, Views are just reframing the grammar in a new context for genomic variables, and Tracks are adding brand new language and syntax to specific to the representation of the genomic data's layout, orientation, alignment, and assembly (L'Yi *et al*, 2022). Therefore, my answer is that the grammar is constantly being recontextualized for specific problems and then truly extended afterwards.

As for the Grammar of Graphics under the scope of blind or low vision people, Zong *et al* (2024) does an excellent job in recontextualizing graphics using Umwelt. The main focus of this program is providing a display with sound cues and sonification to present multimodal representations of data and graphics to avoid presenting the users with a blank slate (Zong *et al*, 2024). The goal is to load data into an interface or editor and break the process into several steps. The editor ends with four actual components: data tab, fields tabs, visual tab, and audio tab. Additionally, any visual tab is required be faceted such that the audio tab can use sonification to describe the visual.

Above is what Zong *et al* (2024) has been proposing for a step in direction of visualizations for the visually impaired. I think some of the ideas work very well, especially sonification to describe plots. As far as the grammar of graphics is concerned, I think we would mainly lose out on aesthetic class, since Umwelt proposes breaking each layer and combination into a series of facets that each graph can read off of by the audio program. Other classes, we might lose would be the first class before algebra as the data would be pre-loaded as well as the algebra class. All data pre-processing would be done before hand as this would be difficult to do via audio or tactile methods. I could see scaling being performed and described to better understand the relationship between the variables, such as basic transformations. Therefore, we have scaling, statistics, geometry, and coordinates to discuss.

For these remaining grammar classes, I think coordinates grids might the trickiest to implement for vision impaired. If we leave the Cartesian grid for the polar grid, then how would we describe this via sonification. Sonification is typically used to describe the ups and downs on a scatter plot or bar chart. However, this can be described using tactile methods to feel the plot and data are circular. Overall, scaling and statistics can be describe audibly, while the geometry can be both described with audio and tactile to measure the ups and downs of the data. Then, the coordinate grid can probably only really be described with tactile methods.
